/*
let a: int = 5 - 7;
let b: int = 1 + 2;
//let d: int = (99 - 88, 5, 7);
let c: int  = a & b;
a = 5;
*/

let a: int;
a = 3;
let b: int;
b = a;
let c: [int; 8];

//a = (c[b + 5]);
c[a - 1] = b;



/*
let b: [int; 5];

(b[0]) = 15;
(b[1]) = 14;
(b[2]) = 13;
(b[3]) = 12;
(b[4]) = 11;
*/

/*
let a: int;
let b: int;
let c: int;
*/

/*
a = 5 - 7;
b = 1 + 2;
c = a & b;
a = 5;
*/
/*
a = 1;
b = 2;
c = 3;

let d: int;

d = (c + a) - 6 + d;
*/
